//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConcorDancer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConcorDancer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap prev {
            get {
                object obj = ResourceManager.GetObject("prev", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;auto-generated&gt;.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;.
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;.
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ///   A strongly-typed resource class, for looking up localized strings, etc..
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;/summary&gt;.
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This class was auto-generated by the StronglyTypedResourceBuilder.
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // class via a tool like ResGen or Visual Studio..
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // To add or remove a member, edit your .ResX file then rerun ResGen.
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // with the /str option, or rebuild your VS project..
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.CodeDom.Compiler.GeneratedCodeAttribute(&quot;System.Resources.Tools.StronglyTypedResourceBuilder&quot;, &quot;2.0.0.0&quot;)].
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.DebuggerNonUserCodeAttribute()].
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //     This code was generated by a tool..
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()].
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class Resources {.
        /// </summary>
        internal static string String21 {
            get {
                return ResourceManager.GetString("String21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private static global::System.Resources.ResourceManager resourceMan;.
        /// </summary>
        internal static string String22 {
            get {
                return ResourceManager.GetString("String22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private static global::System.Globalization.CultureInfo resourceCulture;.
        /// </summary>
        internal static string String23 {
            get {
                return ResourceManager.GetString("String23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute(&quot;Microsoft.Performance&quot;, &quot;CA1811:AvoidUncalledPrivateCode&quot;)].
        /// </summary>
        internal static string String24 {
            get {
                return ResourceManager.GetString("String24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal Resources() {.
        /// </summary>
        internal static string String25 {
            get {
                return ResourceManager.GetString("String25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String26 {
            get {
                return ResourceManager.GetString("String26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;.
        /// </summary>
        internal static string String27 {
            get {
                return ResourceManager.GetString("String27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ///   Returns the cached ResourceManager instance used by this class..
        /// </summary>
        internal static string String28 {
            get {
                return ResourceManager.GetString("String28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;/summary&gt;.
        /// </summary>
        internal static string String29 {
            get {
                return ResourceManager.GetString("String29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //     Runtime Version:2.0.50727.1433.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)].
        /// </summary>
        internal static string String30 {
            get {
                return ResourceManager.GetString("String30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal static global::System.Resources.ResourceManager ResourceManager {.
        /// </summary>
        internal static string String31 {
            get {
                return ResourceManager.GetString("String31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get {.
        /// </summary>
        internal static string String32 {
            get {
                return ResourceManager.GetString("String32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if (object.ReferenceEquals(resourceMan, null)) {.
        /// </summary>
        internal static string String33 {
            get {
                return ResourceManager.GetString("String33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(&quot;ConcorDancer.Properties.Resources&quot;, typeof(Resources).Assembly);.
        /// </summary>
        internal static string String34 {
            get {
                return ResourceManager.GetString("String34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resourceMan = temp;.
        /// </summary>
        internal static string String35 {
            get {
                return ResourceManager.GetString("String35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String36 {
            get {
                return ResourceManager.GetString("String36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return resourceMan;.
        /// </summary>
        internal static string String37 {
            get {
                return ResourceManager.GetString("String37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String38 {
            get {
                return ResourceManager.GetString("String38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String39 {
            get {
                return ResourceManager.GetString("String39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;summary&gt;.
        /// </summary>
        internal static string String40 {
            get {
                return ResourceManager.GetString("String40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ///   Overrides the current thread&apos;s CurrentUICulture property for all.
        /// </summary>
        internal static string String41 {
            get {
                return ResourceManager.GetString("String41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ///   resource lookups using this strongly typed resource class..
        /// </summary>
        internal static string String42 {
            get {
                return ResourceManager.GetString("String42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /// &lt;/summary&gt;.
        /// </summary>
        internal static string String43 {
            get {
                return ResourceManager.GetString("String43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)].
        /// </summary>
        internal static string String44 {
            get {
                return ResourceManager.GetString("String44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal static global::System.Globalization.CultureInfo Culture {.
        /// </summary>
        internal static string String45 {
            get {
                return ResourceManager.GetString("String45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get {.
        /// </summary>
        internal static string String46 {
            get {
                return ResourceManager.GetString("String46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return resourceCulture;.
        /// </summary>
        internal static string String47 {
            get {
                return ResourceManager.GetString("String47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String48 {
            get {
                return ResourceManager.GetString("String48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set {.
        /// </summary>
        internal static string String49 {
            get {
                return ResourceManager.GetString("String49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //     Changes to this file may cause incorrect behavior and will be lost if.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to resourceCulture = value;.
        /// </summary>
        internal static string String50 {
            get {
                return ResourceManager.GetString("String50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String51 {
            get {
                return ResourceManager.GetString("String51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String52 {
            get {
                return ResourceManager.GetString("String52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal static System.Drawing.Bitmap next {.
        /// </summary>
        internal static string String53 {
            get {
                return ResourceManager.GetString("String53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get {.
        /// </summary>
        internal static string String54 {
            get {
                return ResourceManager.GetString("String54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object obj = ResourceManager.GetObject(&quot;next&quot;, resourceCulture);.
        /// </summary>
        internal static string String55 {
            get {
                return ResourceManager.GetString("String55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return ((System.Drawing.Bitmap)(obj));.
        /// </summary>
        internal static string String56 {
            get {
                return ResourceManager.GetString("String56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String57 {
            get {
                return ResourceManager.GetString("String57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String58 {
            get {
                return ResourceManager.GetString("String58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal static System.Drawing.Bitmap prev {.
        /// </summary>
        internal static string String59 {
            get {
                return ResourceManager.GetString("String59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //     the code is regenerated..
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get {.
        /// </summary>
        internal static string String60 {
            get {
                return ResourceManager.GetString("String60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to object obj = ResourceManager.GetObject(&quot;prev&quot;, resourceCulture);.
        /// </summary>
        internal static string String61 {
            get {
                return ResourceManager.GetString("String61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to return ((System.Drawing.Bitmap)(obj));.
        /// </summary>
        internal static string String62 {
            get {
                return ResourceManager.GetString("String62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String63 {
            get {
                return ResourceManager.GetString("String63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String64 {
            get {
                return ResourceManager.GetString("String64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String65 {
            get {
                return ResourceManager.GetString("String65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string String66 {
            get {
                return ResourceManager.GetString("String66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // &lt;/auto-generated&gt;.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //------------------------------------------------------------------------------.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace ConcorDancer.Properties {.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
    }
}
